### PR TITLE
New notebook on using healpix manipulation to find clusters

### PR DESCRIPTION
**Pull request by FalseAnomaly**
A simple notebook that finds clusters using healpix from DES and Legacy Survey catalogs, and compares the results to Redmapper catalog.

@kadrlica

### CODE REVIEW

**Comment by kadrlica** [comment]
@FalseAnomaly This notebook requires some updates before it would be ready to request a Data Lab review. In particular, it requires the addition of some explanatory text to explain the goals and approach that are being taken. Let me know if you'd like to continue with this process, and we can work toward an updated version over the summer.

**Comment by kadrlica** [comment]
@FalseAnomaly let me know if you have any plans to further develop this notebook. Otherwise, I propose that we close this PR.

**Comment by rnikutta** [comment]
@kadrlica Should we close this PR?

**Comment by kadrlica** [comment]
Yes, let's close it.

**Comment by rnikutta** [comment]
Closing this PR.

**Pull request closed without merging**
