### PR TITLE
SPARCL MVP release notebook

### PR DESCRIPTION
**Pull request by jacquesalice**

### CODE REVIEW

**Review by rnikutta — CHANGES_REQUESTED** [review]
Thanks @jacquesalice ! A few final comments, let me know if you want to implement them before I merge.

- The links to the User Manual PDF and the SPARCL website are still behind a VPN.
- Importing from sparcl in a more Python-y way (tested, this works):
```
from sparcl.client import SparclClient
# and then instantiate via
client = SparclClient()
```
- Section titles with capitalization typos:
    - "How to Use SPARCL" --> "How to use SPARCL"
    - "Get Default field names of a data set" --> "Get default field names ..."
    - Get All field names of a data set" --> "Get all field names ..."
    - "Data Discovery I: using SPARCL's ..." --> "Data discovery I: using ..."
    - "Data Discovery II: ..." --> ""Data discovery II: ..."

- Table of alloed constraints is a good idea! It looks better left-aligned. Simply replace
```|:----------------:|:---------------:|:-------:|```
with
```|:-----------------|:----------------|:--------|```

- Data discovery with DL (i.e. sparcl.main) fails if user has an old token (like I just did). Add this to import cell:
```
from dl import authClient as ac
from getpass import getpass
```
And have a (commented out) standard DL login cell:
```
token = ac.login(input("User account [+ENTER]:"),getpass("Password [+ENTER]:"))
```

**Comment by jacquesalice** [comment]
@rnikutta implemented all suggested edits

**Comment by rnikutta** [comment]
Hi @jacquesalice,

- I'm still seeing "Get the Default fields" and "Get All fields" (?) (i.e. capital Default and All)
- For some reason, at least for me on gp12, the TOC links to "Goals & Summary", and to "Authentication" don't seem to be working. I can't explain why, the "anchor" HTML code snippets look ok... Can you check on your side if they are working?

Rest looks fine, thanks!

**Comment by jacquesalice** [comment]
@rnikutta Ok I made the "all" and "default" lowercase, and I fixed the two TOC links that weren't working (they at least now work for me now on gp12)

**Comment by rnikutta** [comment]
Thanks @jacquesalice ! Confirming that all TOC links now work. Merging!

**Pull request merged**
