### PR TITLE
Update File Services NB: SDSS DR14->DR16, add TOC, streamline and mod…

### PR DESCRIPTION
**Pull request by rnikutta**
…ernize a bit.

### CODE REVIEW

**Comment by rnikutta** [comment]
@weaverba137 can you please kindly review the small update to this NB? Thank you.

**Comment by weaverba137** [comment]
Thank you, I will take a look when I get a chance.

**Review by weaverba137 — APPROVED** [review]
I ran the notebook on `gp13` with no errors, so that's good.

I noticed a couple of style quirks where there is a space between a print statement and the function parentheses: `print (`.  That's not technically incorrect, but a Python style analyzer would probably complain about that.  It also makes the code look more like Python 2 than Python 3. There are also 1-2 places with `sc.ls (`.

So just a minor style quibble!

**Comment by rnikutta** [comment]
@weaverba137 I did the stylistic fixes, if you want to take another quick look? Thank you.

**Comment by weaverba137** [comment]
Looks good, go ahead and merge.

**Pull request merged**
