### PR TITLE
Remove redundant SDSS visualization notebook

### PR DESCRIPTION
**Pull request by weaverba137**
This PR:

- [X] Removes `04_HowTos/FileService/How_to_visualize_SDSS_Spectra_with_Bokeh.ipynb` and supporting files.
- [x] Copies some details about visual inspection (VI) to the more modern notebook, `04_HowTos/SPARCL/Plot_SPARCL_Spectra_with_Prospect.ipynb`.
- [X] Updates the kernel on `04_HowTos/QueryClient/How_to_query_DESI_EDR_Data.ipynb`. That's unrelated, but I thought I'd slip it into this PR so I don't forget.

### CODE REVIEW

**Comment by weaverba137** [comment]
I've now copied the useful information from the old notebook into the new notebook. Please review the additional text just before the **DESI** prospect display. Displays for SDSS & BOSS are unchanged.

**Comment by weaverba137** [comment]
Also, this notebook needs to be re-tested after I have installed the latest version of prospect for the DESI 23.1 kernel.

**Comment by rnikutta** [comment]
Hi @weaverba137 is this still in draft state, or ready for review? If ready, can you please assign a reviewer?

**Comment by weaverba137** [comment]
Yes, @jacquesalice, please review.

**Review by jacquesalice — CHANGES_REQUESTED** [review]
@weaverba137 The 2 notebooks run on gp13 and look great! Can you add the HTML versions of the `How_to_query_DESI_EDR_Data` and `Plot_SPARCL_Spectra_with_Prospect` notebooks in this PR as well? Then I'll Approve

**Comment by weaverba137** [comment]
HTML files are now updated.

**Review by jacquesalice — APPROVED** [review]

**Comment by weaverba137** [comment]
*However*, this PR needs to be re-tested after I have installed the latest version of prospect for the DESI 23.1 kernel.

**Comment by weaverba137** [comment]
Nevermind.

**Comment by jacquesalice** [comment]
Oooop, I'll re-test it anyway

**Comment by jacquesalice** [comment]
Tested on gp13 and prospect on the DESI 23.1 kernel still works!

**Comment by rnikutta** [comment]
I think @weaverba137 meant he has yet to install said update on that kernel.

**Comment by weaverba137** [comment]
Prospect 1.3.3 is now installed in the DESI 23.1, and I ran the notebooks with that. No problems.

**Pull request merged**
