### PR TITLE
Add contributed notebooks about LSST simulations with TRILEGAL

### PR DESCRIPTION
**Pull request by gpastorelli-astro**
- Create new directory 05_Contrib/LSST_Sim
- Add README_LSST_SIM.md
- Add single_and_binary_models.ipynb to combine single and binary catalogs
- Add lsst_sim_SGP_plots.ipynb about single stars in the South Galactic Pole
- Add plotting functions in utils.py

### CODE REVIEW

**Comment by jacquesalice** [comment]
Hi @gpastorelli-astro , thanks for the PR! I took a look at the notebooks and have a few minor comments.

**In lsst_sim_SGP_plots.ipynb:**

1. Under the "Getting useful data" section, the sentence "More details are given in Table 4 of the paper" does not include a hyperlink to the paper. When I try to click on the hyperlink it doesn't work. I assume it should link to: https://iopscience.iop.org/article/10.3847/1538-4365/ac7be6#apjsac7be6t4 
2. Under the same section, change:
`umag = R['umag'] # LSST g mag` 
to
`umag = R['umag'] # LSST u mag`
3. Under the "Color-magnitude and color-color diagrams" section, in the cell about 6 panel plots for number counts, you repeat "3." twice.
4. You repeat "3." twice again in the cell about 6 panel plot - CMDs
5. ... And again in the next 6 panel plot cell!
6. Spelling error in the cell below the cell explaining "In the following, we plot the color-color diagrams (g - r) vs. (u - g)...". Change statisticistic --> statistic

**In single_and_binary_models.ipynb:**

1. Under the "Goals" section, change `lsst_sim.dir` --> `lsst_sim.simdr2` and change `lsst_sim.dr2_binary` --> `lsst_sim.simdr2_binary`
2. Under the "Luminosity functions for single and binary stars" section, you repeat "1." twice.
3. In the same cell as above, you repeat `ax1.set_title("Single stars")` twice.
4. Again in the same cell as above, you have a section for `# Axis labels`, but set the xlabel for ax1 and the xlabel for ax2 before this section... 
5. For the Hess diagrams color-coded according to stellar density and the color-color plots, I suggest you include only one colorbar instead of three. You could remove these two lines from both cells:
`make_cbar(ax1, cc, "# star/pixel",  extend = None)`
`make_cbar(ax2, cc, "# star/pixel",  extend = None)`

**Comment by gpastorelli-astro** [comment]
Hi @jacquesalice, thanks for reviewing the notebooks!
I addressed your comments in the latest commit [c07414b](https://github.com/astro-datalab/notebooks-latest/pull/147/commits/c07414b07aeffc95fbf18369ba7d14528f8bd0be)

**Comment by jacquesalice** [comment]
@gpastorelli-astro awesome, thanks! I'm sure @rnikutta will also want to take a look at the notebooks before merging, but he's on vacation until Friday so probably won't get to these until next week.

**Comment by rnikutta** [comment]
Thanks @jacquesalice and @gpastorelli-astro ! I'll go through the NBs myself later today (just back from vacation). Thank you for contributing them!

**Comment by gpastorelli-astro** [comment]
Thanks @rnikutta! Waiting for your feedback

**Comment by rnikutta** [comment]
Thank you @gpastorelli-astro for the contributed NBs and MD file! Below just a few comments and suggestions:

**lsst_sim_SGP_plots.ipynb**
- I recommend to delete the commented-out cell which begins with `'# Uncomment the following to check if your token is valid'`; the cell above (which uses `ac.login())` is sufficient.
- Just for consistency, I recommend to replace "lines of the table" with "rows of the table" in this sentence: "With our selected query, we now retrieve the data and print the number of objects and the first lines of the table"
- For the very first plot (LSST r vs. (g-r) CMD) I propose to make the figure slightly larger, e.g. `(6,6)`, and the plot marker symbol smaller, e.g. `s=0.5` . In addition, an `alpha=0.4` or so would make the features of the CMD a little bit more visible.

**single_and_binary_models.ipynb**
- Same as above, recommend to remove the commented-out cell that starts with "# Uncomment the following to check if your token is valid"
- Remove the cell that defines the function `multimode_gc()`; the function is not used in this notebook.
- In the very first plot (luminosity functions), right panel title says "stars stars" (duplicate)
- In the first code cell in section "CMDs and CCDs", remove the commented-out line `#get_2Dhess_param(gmag60-rmag60, rmag60, None, stat='count', bins=bins)` (I assume it's an artifact left over from testing).

Thanks again, very nice NBs!

**Comment by gpastorelli-astro** [comment]
Thanks, @rnikutta! I modified the NBs according to your suggestions.

**Comment by rnikutta** [comment]
Thank you @gpastorelli-astro , merged into master branch!

**Pull request merged**
