### PR TITLE
Replicate DESI's official database tutorial notebook

### PR DESCRIPTION
**Pull request by weaverba137**
This PR adds a notebook that tries to replicate the functionality of [DESI's official database tutorial](https://github.com/desihub/tutorials/blob/main/database/spectroscopic-production-database.ipynb) as closely as possible.

The official notebook has not yet been finalized, so this PR is also a Work In Progress.

### CODE REVIEW

**Comment by weaverba137** [comment]
@jacquesalice @rnikutta @stephjuneau, today is a very busy day, but I hope I can test this later today or on Tuesday.

One question is: does this notebook overlap in functionality with other DESI EDR notebooks that are also in the pipeline?

**Comment by weaverba137** [comment]
Thank you @stephjuneau!

**Comment by jacquesalice** [comment]
Hi @weaverba137 I know you're still working on this notebook but I have a few comments/questions/error reports. 

1. Do you plan to add more to the Table of Contents? If not, this section should be removed.
2. I assume the `qc.set_profile('db01')` in the imports cell was before the DESI tables moved to prod, so this line can be removed.
3. The cell with `def moon` gives me an error: `NameError: name 'ephem' is not defined`. Then when I try to uncomment the `ephem = get_ephem()` and `from desisurvey.ephem import get_ephem, get_object_interpolator` in the imports cell, I get another error: `ModuleNotFoundError: No module named 'ephem'`. Does this need to be installed?
4. I remember a conversation about leaving the `version` table out of the ingest at Data Lab. So, it should be removed from the "The tables" section and the "Versions" section should probably be removed. However, if the `version` table _should have_ been included in the ingest, let me know and I can work on getting it in the database.
5. In the "Initial Database Connection" section, trying to run the cell to create a ~/.pgpass file gives me an error: `cp: cannot stat ‘/global/common/software/desi/desi_public.pgpass’: No such file or directory`
6. In order to run the cell in the "Establish connection" section, I had to uncomment the `from desiutil.log import get_logger, DEBUG` and `import specprodDB.load as db` lines in the import cell.
7. I get an error when trying to run the cell that uses `inspect()`: `NoInspectionAvailable: No inspection system is available for object of type <class 'NoneType'>`
8. In the "Another Simple Join" section, there is a lot of noisy output from the query. May I suggest two things: (1) change limit from 50 --> 20 and (2) change the output format to pandas so the call to the queryClient looks like:
```
response = qc.query(sql=q, fmt='pandas', timeout=600)
response
```

The rest of the notebook looks like it's still in draft form since a lot of the cells produce errors, so I'll stop here for now.

**Review by jacquesalice — CHANGES_REQUESTED** [review]
Hi @weaverba137 I know you're still working on this notebook but I have a few comments/questions/error reports. 

1. Do you plan to add more to the Table of Contents? If not, this section should be removed.
2. I assume the `qc.set_profile('db01')` in the imports cell was before the DESI tables moved to prod, so this line can be removed.
3. The cell with `def moon` gives me an error: `NameError: name 'ephem' is not defined`. Then when I try to uncomment the `ephem = get_ephem()` and `from desisurvey.ephem import get_ephem, get_object_interpolator` in the imports cell, I get another error: `ModuleNotFoundError: No module named 'ephem'`. Does this need to be installed?
4. I remember a conversation about leaving the `version` table out of the ingest at Data Lab. So, it should be removed from the "The tables" section and the "Versions" section should probably be removed. However, if the `version` table _should have_ been included in the ingest, let me know and I can work on getting it in the database.
5. In the "Initial Database Connection" section, trying to run the cell to create a ~/.pgpass file gives me an error: `cp: cannot stat ‘/global/common/software/desi/desi_public.pgpass’: No such file or directory`
6. In order to run the cell in the "Establish connection" section, I had to uncomment the `from desiutil.log import get_logger, DEBUG` and `import specprodDB.load as db` lines in the import cell.
7. I get an error when trying to run the cell that uses `inspect()`: `NoInspectionAvailable: No inspection system is available for object of type <class 'NoneType'>`
8. In the "Another Simple Join" section, there is a lot of noisy output from the query. May I suggest two things: (1) change limit from 50 --> 20 and (2) change the output format to pandas so the call to the queryClient looks like:
```
response = qc.query(sql=q, fmt='pandas', timeout=600)
response
```

The rest of the notebook looks like it's still in draft form since a lot of the cells produce errors, so I'll stop here for now.

**Comment by weaverba137** [comment]
Thank you for the comments.  This is indeed still a work in progress, so I will be sure to incorporate the suggested changes.

**Comment by weaverba137** [comment]
@jacquesalice @stephjuneau this is now ready for review.

1. I addressed all of @jacquesalice 's previous comments.
2. I picked the directory arbitrarily, so if this notebook should be moved elsewhere, please let me know.
3. I have not generated an HTML copy yet.

**Comment by weaverba137** [comment]
OK, I've addressed everything, please take a look.  However, I kept the `from desitarget.targetmask import (desi_mask, mws_mask, bgs_mask)`, and now I'm actually using `desi_mask`.

I've also added an HTML version.

I can make further changes until about 12:00 MST, but earlier would be better.

**Comment by rnikutta** [comment]
Thanks @weaverba137 
- Ok re `desi_mask`. But `mws_mask` and `bgs_mask` are not being used, right? So let's not import them.
- Can you also comment out the `ac.whoAmI()` line? This will prevent the username who last ran the NB to show. If...
- ... you also agree to leave the outputs with the NB (which we generally like, because the NB then previews nicely on GH; unless a NB has very heavy outputs (in the 10+ MB range). (BTW, for the longer table outputs, you could activate output scrolling (just for those cells)
- There's one empty cell at the very end of the NB. Remove it.
- Finally, just update the `__version__` string to today, and we can merge.
Many thanks!

**Comment by weaverba137** [comment]
OK, I'll make those changes momentarily.

**Comment by rnikutta** [comment]
@jacquesalice Can you please sign off on your review of @weaverba137 's NB? I currently can't merge (without overriding) unless you sign off on it ;-) Thanks.

**Comment by stephjuneau** [comment]
Hi @rnikutta @weaverba137 @jacquesalice I think it's already been agreed to leave this notebook in the HowTos/ folder. I wanted to mention that I suggesting linking it among a compilation of notebook links for a short Mirror article on DESI EDR. I'm not sure whether the compilation of links will make it to the final publication, but I'm giving it a try! Also, I propose adding a README file to the 03_ScienceExamples/DESI/ folder to point to that notebook and to the HowTo on SPARCL. I will work on this today and send it for approval.

**Comment by rnikutta** [comment]
Sounds good @stephjuneau . I'll merge after your commit.

**Comment by rnikutta** [comment]
Better start a new branch, and a new PR @stephjuneau . I'll merge Ben's branch now, so that it shows up on master. (sorry @jacquesalice , going to override!)

**Comment by rnikutta** [comment]
@stephjuneau Merged!

**Pull request merged**
