### PR TITLE
Temp fix to pip install cell

### PR DESCRIPTION
**Pull request by jacquesalice**
This is a re-PR from [PR#174](https://github.com/astro-datalab/notebooks-latest/pull/174) that temporarily replaces the pip install cell to install the most recent sparclclient version. We are waiting for the sparclclient to be updated on gp12. Assigning to @rnikutta as reviewer to Approve and merge

### CODE REVIEW

**Comment by rnikutta** [comment]
@jacquesalice Two things, please clarify:
1) sparclclient is already updated (as of this afternoon): `import sparcl; sparcl.__version__` --> '1.2.0'
2) This temp fix PR now has conflicts with master.

Do we really need this temp fix?

**Comment by jacquesalice** [comment]
@rnikutta oh, it is? Was Mike able to update the stack? If it has been updated, then you're right this temp fix is not necessary. This branch is getting a little messy, so I think I'm just going to create a new branch with a new PR and add the notebook there (keeping the pip install cell as it was). Sorry!

**Comment by rnikutta** [comment]
@jacquesalice sorry I thought I had included you in the emails (but it was only Mike, Igor, Stephanie).

Do you need to make a new branch? Just close this PR #178, and we're good, no?

**Comment by jacquesalice** [comment]
@rnikutta oh.....! That would've been useful info!! But the notebook that's currently in Master isn't the updated one with DESI EDR. So yes I do need to create a new PR and close this one. The new PR is here: https://github.com/astro-datalab/notebooks-latest/pull/179

**Comment by jacquesalice** [comment]
Closed. See new PR here: https://github.com/astro-datalab/notebooks-latest/pull/179

**Pull request closed without merging**
