### PR TITLE
Gp13updates

### PR DESCRIPTION
**Pull request by rnikutta**
Fixing 2 data reduction NBs for gp13, by re-running them with the updated kernels.

### CODE REVIEW

**Comment by rnikutta** [comment]
@jacquesalice and @bmerino95 can you please review these NBs. Just execute on gp13 to confirm that they work. Don't change the kernel, this is precisely the test: "do they run with the newly assigned kernels"? Thanks.

**Comment by bmerino95** [comment]
Hi @rnikutta. I loaded both notebooks into GP13 and was able to run DataReductionPyrafGMOS.ipynb without a problem because it automatically changed the kernel to Gemini (Py3.8). However, DataReductionDragonsGMOS.ipynb stayed in the Python 3 kernel and crashed while trying to run the first cell because it could not find the DRAGONS libraries.

**Comment by rnikutta** [comment]
Thanks for trying it out @bmerino95 . Just to make sure: did you switch the branch, after cloning the repo on gp13?

**Comment by bmerino95** [comment]
@rnikutta Thank you for pointing that out! I was on the wrong branch. This time DataReductionDragonsGMOS.ipynb successfully opened the DRAGONS (Py3.7) kernel and ran without any issues.  I also retested DataReductionPyrafGMOS.ipynb and it also worked without any issues.

**Comment by rnikutta** [comment]
Great, many thanks @bmerino95 Can you please submit your review with "Approve" option selected, so that I can merge (w/o having tom override ;-))

**Review by bmerino95 — APPROVED** [review]
Both Jupyter notebooks run on GP13 and automatically open the appropriate kernels.

**Review by jacquesalice — APPROVED** [review]

**Comment by rnikutta** [comment]
Thanks for your reviews @bmerino95 and @jacquesalice. Merged.

**Pull request merged**
