### PR TITLE
Add "BaryonicAcousticOscillations" project on extra-galactic science

### PR DESCRIPTION
**Pull request by JasonWooo**
Added notebook "BaryonicAcousticOscillation_BOSSDR12_20230518", which is a detailed instruction on characterizing the baryonic acoustic oscillations using SDSS DR12 data using two-point correlation functions.

### CODE REVIEW

**Comment by kadrlica** [comment]
Thanks @JasonWooo! 

As context for others: this submission is part of the final project for ASTR285 at UChicago. I plan to review the notebook before requesting review from a repo admin.

**Comment by kadrlica** [comment]
@JasonWooo I think this notebook would be ready for Data Lab review with some fairly minor changes. Let me know if you'd like to go forward with that process. I can leave some suggestions here and/or make some changes directly to the notebook.

**Comment by JasonWooo** [comment]
Sure! I will be traveling tomorrow but I'll let you know once I'm settled down to work on things!

**Comment by kadrlica** [comment]
@jacquesalice and @rnikutta would you have a chance to give this notebook a review? Thanks!

**Comment by rnikutta** [comment]
Hi @kadrlica and @JasonWooo , gladly! Thanks for the NB. I'm still on vacation but will try to take it for a spin on Thu or Fri.

**Comment by jacquesalice** [comment]
Thank you @JasonWooo and @kadrlica for the notebook! It looks great! A few minor comments:

1. Under the Goals section, mention which figure from Eisenstein et al 2004 you will be replicating. 
2. Under the "Loading Galaxy Data" section, the link to the SDSS page gave me an error. Looks like it should be this instead? https://classic.sdss.org/dr7/products/general/edr_html/node53.php 
3. For the plots in the section "Visualization of the Dataset", add units to the axes labels. Like "RA (deg)" and "Dec (deg)". 
4. In the mollweide plot in this same section, what does the colorbar represent? Add a label with units.
5. Misspelled "Random" in "Loading Radom Data" section title.
6. For the plots in the section "Loading Random Data", add units to the axes labels.
7. In the "Calculate two-point correlation function estimator" section, you provide an equation for the estimator to calculate the correlation function. Add a description (plus units where applicable) of what each component of this equation means (it looks like dd = galaxy-galaxy pair counts, rr = random-random pair counts, and dr = galaxy-random pair counts ?)
8. In "Co-Moving Distances" section, misspelled "correlation" in the first sentence as "correclation".
9. Also in this section, add a description (plus units where applicable) of what each component of the equation for "traditional definition for comoving distance" means.
10. Again in this section, you mention "the correlation function  𝜉(𝑟) obtained from treecorr is multiplied with 𝑟^2 to better demonstrate the peak." What is "r"?
11. What does the "L-S" in the plot title "L-S Spatial Correlation" stand for? Large-Scale? Or Landy-Szalay? Maybe mention that in the title. Like "Landy-Szalay (L-S) Spatial Correlation".
12. In the "Fitting the Accoustic Feature" section, add a description (plus units where applicable) for each component in the distance combination equation and the equation after.

Thank you again for the notebook, @JasonWooo you did an amazing job!

**Review by jacquesalice — CHANGES_REQUESTED** [review]
Thank you @JasonWooo and @kadrlica for the notebook! It looks great! A few minor comments:

1. Under the Goals section, mention which figure from Eisenstein et al 2004 you will be replicating. 
2. Under the "Loading Galaxy Data" section, the link to the SDSS page gave me an error. Looks like it should be this instead? https://classic.sdss.org/dr7/products/general/edr_html/node53.php 
3. For the plots in the section "Visualization of the Dataset", add units to the axes labels. Like "RA (deg)" and "Dec (deg)". 
4. In the mollweide plot in this same section, what does the colorbar represent? Add a label with units.
5. Misspelled "Random" in "Loading Radom Data" section title.
6. For the plots in the section "Loading Random Data", add units to the axes labels.
7. In the "Calculate two-point correlation function estimator" section, you provide an equation for the estimator to calculate the correlation function. Add a description (plus units where applicable) of what each component of this equation means (it looks like dd = galaxy-galaxy pair counts, rr = random-random pair counts, and dr = galaxy-random pair counts ?)
8. In "Co-Moving Distances" section, misspelled "correlation" in the first sentence as "correclation".
9. Also in this section, add a description (plus units where applicable) of what each component of the equation for "traditional definition for comoving distance" means.
10. Again in this section, you mention "the correlation function  𝜉(𝑟) obtained from treecorr is multiplied with 𝑟^2 to better demonstrate the peak." What is "r"?
11. What does the "L-S" in the plot title "L-S Spatial Correlation" stand for? Large-Scale? Or Landy-Szalay? Maybe mention that in the title. Like "Landy-Szalay (L-S) Spatial Correlation".
12. In the "Fitting the Accoustic Feature" section, add a description (plus units where applicable) for each component in the distance combination equation and the equation after.

Thank you again for the notebook, @JasonWooo you did an amazing job!

**Comment by rnikutta** [comment]
Really nice NB @JasonWooo and @kadrlica , many thanks! Below my comments in addition to @jacquesalice 's, trying not to repeat any:

- In Summary section: "using data from the The Baryon Oscillation Spectroscopic Survey (BOSS)" --> "using data from The Baryon Oscillation Spectroscopic Survey (BOSS)"
- "released a part of the SDSS DR12" --> "released as part of SDSS DR12"
- If there is a good public link to "ASTR285 Science with Large Astronomical Surveys", you could link it... (in Summary section)
- In "Early Universe": "The early universe is so hot and dense that matter existed in the form of plasma" --> "was so hot"
- "Thompson scattering" --> "Thomson scattering"
- Remove unused imports:
  - glob
  - inspect
  - from importlib import reload
  - warnings
  - import matplotlib as mpl; since you're already importing `plt`, you can replace the single `mpl` use by: `plt.rcParams.update(mpl.rcParamsDefault)`
  - import pandas as pd

- "Loading Galaxy Data" section: We have the SDSS DR12 files at Data Lab, in the `sdss_dr12://` file service. Using the file service to fetch the files will make a stronger connection of the NB to DL, and it simplifies the NB. I propose that you:

  - Add this line to the Import cell:

    ```
    from dl import storeClient as sc
    ```

  - Replace the "Loading Galaxy Data" section with this:

Loading Galaxy Data

Load the CMASS data sample from the Baryon Oscillation Spectroscopic Survey (BOSS). Only the Southern half of the survey is used. The analysis could extend to the full dataset, but this is sufficient for the purposes of seeing the BAO. The dataset is pre-selected for Luminous Red Galaxies (LRGs) using two different color selections for low-redshift (𝑧<0.45) and high-redshift (𝑧>0.45) galaxies. The specifics are noted in this SDSS page.

We get the FITS file from the `sdss_dr12` File Service at Data Lab:

```
remdir = 'sdss_dr12://boss/lss/'  # remote
locdir = './data/'                # local
fname = 'galaxy_DR12v5_CMASSLOWZTOT_South.fits.gz'

if not os.path.exists(locdir+fname):
    res = sc.get(fr=remdir+fname,to=locdir+fname,verbose=False)
```

Load the data and print the fields and number of objects in the dataset.

```
data = fits.open(locdir+fname)[1].data
print(data.dtype)
print(f'{len(data)} objects in data set')
```

- Same for the "Random Data" section. The file is on our `sdss_dr2://` file service. You can replace the wget cell with:

  ```
  fname = 'random0_DR12v5_CMASSLOWZTOT_South.fits.gz'

  if not os.path.exists(locdir+fname):
      res = sc.get(fr=remdir+fname,to=locdir+fname,verbose=False)
  ```

  and the data loading cell with:

  ````
  rand = fits.open(locdir+fname)[1].data
  print(rand.dtype)
  print(f'{len(rand)} points in total in random')
  ````

- "The random dataset would, however, be hard to construct in this case, as the SDSS random does not come with magnitudes assigned." --> Explain here briefly what is "SDSS random".

- First two-panel plot in Section "Visualization of the Dataset": Alice already asked for a colorbar with units for the right-hand plot. Please also consider replacing the panel titles, from "Scatter" to "Distribution in the sky", and from "Density" to "Object density".

- Same for the Scatter and Density plot in Section "Loading Random Data".

- "Show a mollwide visualization" --> "Show a Mollweide visualization"

- In the Mollweide view, the colorbar needs a label and units, i.e. log_10(objects/X) where you decide on X (square degree, square arcsec, sterad?), and compute the correct number given that NSIDE is 32 (which corresponds to a healpixel size of 1.0226539 * 10-3 sterad)

- In one cell, remove the commented-out line `#rand_cut = rand`

- Similar to Alice's comment about explaining the meaning of all symbols used in the Landy-Szalay estimator, the key function `tpcf_ls()` should have a longer docstring, explaining all parameters.

- Decide on one way to write this, either 'LCDM' or '\Lambda CDM' throughout the NB.

- The function `calc_Dv()` is defined, but not used. A bit of a letdown ;-) Would you consider either demonstrating the usage of it, or to remove it from the NB?

**Comment by JasonWooo** [comment]
Hi @kadrlica @jacquesalice @rnikutta ,

Thank you all for the feedback and suggestions! I've made changes to the notebook, incorporating all the changes and fixing all the issues that were pointed out. Two notes from me:

- @rnikutta , I left the old download code cells in as comments, in case the notebook is accessed without Datalab support. Feel free to delete them.
- Some variables (such as r in the tpcf_plot function) were never used but kept to avoid confusion.

That's it from me! Please do let me know if there is anything else I can do. Have a good weekend!

**Comment by galaxyumi** [comment]
Hi @JasonWooo and @kadrlica, as a new member, I just reviewed your NB. The contents are great. Thanks for your contribution!

I have only minor suggestions:
1. In the Background, Baryonic Acoustic Oscillations (BAO) -> Baryonic Acoustic Oscillations (BAOs) 
2. Please double check the year of the Eisenstein's paper. It seems that it should be Eisenstein et al. (2005), not  Eisenstein et al. (2004).
3. In Magnitude section, could you specify a section, or a table, or equations for this statement: "The magnitudes are given in five different versions of fluxes, using definitions provided in Eisenstein et al 2004."?
4. Can you replace the link for Anderson et al. (2012) to the published version (https://ui.adsabs.harvard.edu/abs/2012MNRAS.427.3435A/abstract), not the arXiv version?

**Comment by JasonWooo** [comment]
Hi @galaxyumi,

Thank you for all the valuable feedback! I incorporated them into the notebook and pushed to my fork of notebooks-latest. For suggestion #4 in particular, I also changed all arxiv links to published versions from their respective journals.

Thank you all again for following through with this project. Please let me know if there is anything else I can do @kadrlica @rnikutta @jacquesalice

**Review by jacquesalice — APPROVED** [review]

**Comment by jacquesalice** [comment]
Thanks @JasonWooo ! It looks great. Merging to master now :)

**Pull request merged**
