### PR TITLE
Example of using gravitational wave data with the ANTARES devkit

### PR DESCRIPTION
**Pull request by nesquivelr**
Hi 👋,

We recently added gravitational wave data in ANTARES and this PR adds a jupyter notebook to show users how to access this data and use these new functionalities. 

Thanks!

### CODE REVIEW

**Review by rnikutta — CHANGES_REQUESTED** [review]
Thank you @nesquivelr for the new contributed NB!

Here my comments and suggestions. The last one requires an update from our side; I'll do that over the weekend.

Feel free to implement these first. @jacquesalice may have some additional comments afterwards.

- Note the date format in __version__ (it's supposed to be yyyymmdd, i.e. year-month-day)

- Rename directory (to be consistent with the other AntaresDevKit directory):

    05_Contrib/TimeDomain/AntaresDevkitGravitationalWaves/

    to 

    05_Contrib/TimeDomain/AntaresDevKitGravitationalWaves/  # capital K in 'DevKit'

- Rename the ipynb and html notebook files to be consistent with the mother directory name:

    AntaresGravitationalwavesDevKit.[html|ipynb]

    to

    AntaresDevKitGravitationalWaves.[html|ipynb]
    
    (note there are two changes: order or words, and capital W in 'Waves')

- Thanks for adding a new keyword to keywords.txt, that's very thoughtful. Can you please move the new keyword to its alphabetically correct position? (the list is sorted)

- The TOC Content section starts enumerating at 0. Is this desired? Or do you want to start at 1?

- TOC: Change "1. What Is a Gravitational Wave?" to "1. What is a gravitational wave?" Same in the actual section header.

- in Summary section: change "jupyter" to "Jupyter", add a full stop at the end of the sentence, and say which "notices" (GCN). See below for more on this.

- In "0. Background information on ANTARES", many words are capitalized (e.g. Alert, Locus, Filter) even when they don't mean a Python class or instance. Can you please use lower-case when you describe, e.g. "an alert", "a filter", or "a locus"? It's ok to use "Locus" etc. when you mean the Python object. Please also use lower-case for "gravitational wave".

- Change this sentence:

    "We can access to the gravitational wave events associated with a locus by accessing to the `grav_wave_events_metadata` dictionary"

    to:

    "We can access the gravitational wave events associated with a locus through the `grav_wave_events_metadata` dictionary"

- It would be good to name explicitly where ANTARES is getting the gravitational wave events from (GCN). You link to the ANTARES description: https://nsf-noirlab.gitlab.io/csdc/antares/antares/grav_waves.html, which mentions GCN. But please name GCN (make it a link) in the notebook as well, for instance in Section "2. How to access to gravitational wave notices using the ANTARES devkit?", and also in the Summary section (for instance, the sentence there could be: "This Jupyter notebook is an example of how to access to gravitational wave notices (GCN) using the ANTARES devkit and client" (where you make "GCN" a link to the GCN website.

- Fix this sentence:

  "If we want to access to the gravitational wave events associated with an alert, we can access to the `grav_wave_events` variable".

  Maybe like this?

  "We can access the gravitational wave events associated with an alert through the `grav_wave_events` variable"

- Fix this sentence:

    "If we want to access to more information about a gravitational wave we can use its gracedb_id to search it in treasuremap".

    For instance like this:

    "We can use the `gracedb_id` property to search for an event in the treasuremap"

- In Section 3, add another "on" to this sentence:

    "When developing a filter using the devkit we can restrict the alerts that the filter will be ran on based on the probability region"

- In the code cell that defines `class SomeFilter`, should the printed string be:

    "Number of gravitational wave notices: ..." ?

- Section 4 headline: change from "4. How to access to gravitational wave notices using the ANTARES client?" to "4. How to access gravitational wave notices using the ANTARES client?". Change also in the TOC.

- Section 4 first sentence: change from "For cases when we want to access to a gravitational wave notice by the id we can use some methods of the antares_client available in [URL]" to "For cases when we want to access a gravitational wave notice by ID we can use methods of the antares_client, described at [URL]"

- Finally, we have recently updated our "Disclaimers" at Data Lab. But we haven't yet updated the notebook template accordingly. I'll do that over the weekend, and will post another comment on this PR.

**Comment by nesquivelr** [comment]
Hi @rnikutta, thank you for reviewing this pull request. I added all your suggestion to the code. Here are my comments:
- Regarding the TOC, starting from 0 is the desired numbering since the other ANTARES Jupyter notebooks start with the same number.
- I added the GCN link in some parts of the notebook, I don't know if this is what you meant, let me know if I misunderstood please.
- I'll be looking forward to the disclaimer update to finishing updating this notebook.

**Review by jacquesalice — CHANGES_REQUESTED** [review]
@nesquivelr thanks for the revised notebook! I have a few additional comments:
1. In the Summary section, I see Robert suggested the sentence "This Jupyter notebook is an example of how to access to gravitational wave notices (GCN) using the ANTARES devkit and client", but there's a "to" that shouldn't be there. So change it to: "This Jupyter notebook is an example of how to access gravitational wave notices (GCN) using the ANTARES devkit and client"
2. Same in Section 2 title, remove the "to" between "access" and "gravitational" 
3. In Section 4, I'd recommend using a different example ID/datetime than the one that's already used in the https://nsf-noirlab.gitlab.io/csdc/antares/client/tutorial/searching.html example. 
4. Also in Section 4, can you add a brief description of what `antares_client.search.get_grav_wave_notices` is doing that `antares_client.search.get_latest_grav_wave_notices` isn't? 
5. Also also in Section 4, add a sentence about what the `datetime` refers to? (`notice_datetime`? `event_datetime`?) What does it mean?

**Comment by nesquivelr** [comment]
@jacquesalice thanks for reviewing these changes. I updated the Jupyter notebook including all your suggestions

**Review by jacquesalice — APPROVED** [review]

**Review by rnikutta — APPROVED** [review]

**Comment by rnikutta** [comment]
Hi @nesquivelr apologies for the long delay. We decided to merge your NB and we will update the Acknowledgments section ourselves at a later time. Thank you for contributing this NB!

**Pull request merged**
