### PR TITLE
Photometric reverberation mapping contribution

### PR DESCRIPTION
**Pull request by cefeida42**
Hello,

this is a contribution **PhotometricReverberationMappingAGN** (notebook and its auxiliary files). It is a tutorial for performing photometric reverberation mapping. The notebook shows how to download or generate light curve data and it introduces the tools and steps needed for this type of analysis. 

Some info regarding the contribution:
- I tested it on my Astro Data Lab account using the Python3 kernel - it is error-free.
- I added one new keyword in the meta cell at the beginning of the notebook: 'reverberation mapping'.

### CODE REVIEW

**Comment by jacquesalice** [comment]
Hi @cefeida42 , this looks awesome! A few minor comments:

1. In the description under Part I number 1, add a link to the AnatresVariableRCBStars notebook (https://github.com/astro-datalab/notebooks-latest/blob/master/05_Contrib/TimeDomain/AntaresExample/AntaresVariableRCBStars.ipynb)
2. Misspelled "successful" and "corresponds" in the following sentence under the first ANTARES API elastic search cell: "We had only one succesfull hit out of five and it coresponds to 'SDSS J081109.38+172928.9' from our catalog."
3. In the cell that plots the Light curve of Locus_id=ANT2020pn2g4, I suggest you break up the long lines of `plt.ylim` and `plt.scatter` like this:
```
plt.ylim(max(lc_data['ztf_magpsf'])+0.1*(max(lc_data['ztf_magpsf'])-min(lc_data['ztf_magpsf'])),
         min(lc_data['ztf_magpsf'])-0.1*(max(lc_data['ztf_magpsf'])-min(lc_data['ztf_magpsf'])))
plt.scatter(lc_data['ant_mjd'][lc_data['ztf_fid']==2], lc_data['ztf_magpsf'][lc_data['ztf_fid']==2],
            c='red', alpha=0.5, label=r'$r$ band')
plt.scatter(lc_data['ant_mjd'][lc_data['ztf_fid']==1], lc_data['ztf_magpsf'][lc_data['ztf_fid']==1],
            c='green', alpha=0.5, label=r'$g$ band')
```
4. Sometimes you use "catalog" and other times you use "catalogue", use one form throughout the notebook for consistency.
5. Misspelled "respectively" in the following sentence at the end of number 2: "This is significant improvement compared to ANTARES light curves, where we had only 20 and 34 points in the g and r  bands, rescpectively."
6. I get the following error when trying to run the second cell under the "Step 2 & 3: Calculate ACF and CCF using pyZDCF" section: `FileNotFoundError: [Errno 2] No such file or directory: './results/acf.dcf'` since I do not have an output directory called './results'. Can you add an empty folder called 'results' to the PhotoReverberationMappingAGN directory?
7. Add units to the axes in the plot "CCF and ACF using pyZDCF"
8. Under the section "Step 5: Estimate the time lag", add a link to the Laursen et al. 2019 paper.

Thanks!

**Comment by cefeida42** [comment]
Hi @jacquesalice!

Thank you for your detailed and prompt review! I made all of the suggested corrections. Additionally, I included all the files that the notebook generates when running from beginning to end in full, to mitigate potential errors. The folder structure should be good now. Let me know if you have more suggestions.

**Comment by jacquesalice** [comment]
Thank you! I'm sure @rnikutta will also want to take a look through the notebook before we merge it to production.

**Comment by rnikutta** [comment]
Really a great NB @cefeida42 , many thanks for contributing it to DL! I'm sending my comments in an email in a second. Please simply push another commit with the changes to amend this PR, and we'll merge it from here.

**Comment by cefeida42** [comment]
@rnikutta, thank you so much for the detailed review, I addressed all of your comments. Let me know if there is anything else I need to change or add. Happy to contribute to the fantastic Astro Data Lab :)

**Review by rnikutta — APPROVED** [review]
Thank you @cefeida42 this is most excellent! Merging this PR. More in email.

**Pull request merged**
