### PR TITLE
testnotebooks.py code now traps two kernel exceptions: DeadKernelErro…

### PR DESCRIPTION
**Pull request by rnikutta**
…r (likely due to RAM exhaustion), and NoSuchKernel. The test suite continues with the next NB in both cases, rather than quiting.

### CODE REVIEW

**Review by iglesu — COMMENTED** [review]
The only review I'd made is if we want to trap any generic exception, DeadKernelError and NoSuchKernel are the expected ones but what about the unexpected?
e.g. adding last 

except Exception as e:
    cprint(f"KERNEL DIED UNKWN EXC: {e}", 'red')

**Comment by rnikutta** [comment]
Thank you @iglesu ! Added generic Exception trap. Please approve if you are satisfied.

**Review by iglesu — COMMENTED** [review]
cprint('AN EXCEPTION OCCURRED: %e' % e,'red')

Isn't "%e" used for scientific notation?, I might be wrong but a %s should suffice
cprint('AN EXCEPTION OCCURRED: %s' % e, 'red')

**Comment by rnikutta** [comment]
Ouch, a typo! Thanks for catching it @iglesu . Fix committed, please review/approve.

**Review by iglesu — APPROVED** [review]
Great! thank you!

**Pull request merged**
