### PR TITLE
Updates to NB test suite.

### PR DESCRIPTION
**Pull request by rnikutta**
- Update testnotebooks.[py|ipynb] such that list of NBs to be processed is computed separately from the run() call.
- Update deprecated .mapapply() from pandas to .map()
- Update references to 'noao' in tests/ dir
- Update tests/README.md
- Update one screenshot used in README.md
- Add DRAGONS GSOI and LongSlitGMOS data reduction NB to exclude list of b/c of their long runtime.

### CODE REVIEW

**Review by jacquesalice — CHANGES_REQUESTED** [review]
@rnikutta All looks pretty good! Just a few things:
- For `__author__`, we format it as a single string. So instead of 
```
__author__ = ['Robert Nikutta <robert.nikutta@noirlab.edu>', 'Data Lab Team <datalab@noirlab.edu']
```
It should be:
```
__author__ = 'Robert Nikutta <robert.nikutta@noirlab.edu>, Data Lab Team <datalab@noirlab.edu>'
```
- `__author__` should come before `__version__` in both the .ipynb and .py files (to match all of our other notebooks)
- Add `Data Lab Team <datalab@noirlab.edu>` to author list in the .py file
- Did you want to add a `__nbid__` for this notebook?
- Remove `%%time` in the cell under the "Run the test suite" section, and update the `view_run_results.png` so it doesn't show this cell running with `%%time`

**Typos in the cell under the "Set up which notebooks to test, and which to exclude from testing" section (in both .ipynb and .py files):**
- `../01_GetttingStartedWithDataLab/` --> `../01_GettingStartedWithDataLab/`
- `directries` --> `directories`
- `any number if intermediate characters` --> `any number of intermediate characters`

In the README.md:
- The steps in the "Steps: On the Data Lab Jupyter notebook server" section are missing step # 3. It currently goes step 1, 2, 4, 4, 5, 6.
- In the "Steps: On your local Jupyter / JupyterLab or in the terminal" section, for step # 3, I think it should say `Follow the steps 3-6 under "Steps: On the Data Lab Jupyter notebook server" above.` instead of `Follow the steps 4 and 5 under "Steps: On the Data Lab Jupyter notebook server" above.`

**Comment by rnikutta** [comment]
@jacquesalice thank you for your PR review. Implemented all comments (please see commit message).

**Review by jacquesalice — CHANGES_REQUESTED** [review]
@rnikutta A couple more quick fixes (see comments below), then this PR should be good to merge!

**Comment by rnikutta** [comment]
@jacquesalice Done!

**Review by jacquesalice — APPROVED** [review]
@rnikutta great! Approved 👍

**Pull request merged**
