### PR TITLE
Add new GMOS Pyraf data reduction NB

### PR DESCRIPTION
**Pull request by rnikutta**
Data reduction example NB to showcase usage if the Gemini IRAF kernel at DL. NB contributed by Vini P and Brian M from US-NGO. @jacquesalice can you please review it?

### CODE REVIEW

**Comment by jacquesalice** [comment]
@rnikutta will do! Should I leave my comments in this PR or email Brian and Vini directly?

**Comment by rnikutta** [comment]
@jacquesalice You can make the comments right here on GH, thanks,

**Comment by jacquesalice** [comment]
@vmplacco @rnikutta  I'm having an issue with the cell that uses bash and wget to download the FITS files from the Gemini archive. I'm running the notebook on the Data Lab notebook server under in this directory: `~/notebooks_20230123_193855/04_HowTos/DataReduction/PyrafGMOS/`. But when I run the cell to download the files, it saves them in my `~/` directory and the rest of the notebook gives me errors like:
```
ERROR - GSREDUCE: Input image : N20190302S0248.fits does not exist
ERROR - GSREDUCE: Exiting with 1 errors
 
ERROR - GSREDUCE: Program execution failed with 1 errors
 
GSREDUCE done
```

**Comment by vmplacco** [comment]
Hi Alice,

Yes, it assumes that you're running on your home directory. If you do:

import os
os.chdir(~/notebooks_20230123_193855/04_HowTos/DataReduction/PyrafGMOS/)

would it work?

Best,
Vini

**Comment by jacquesalice** [comment]
@vmplacco ah yes! That worked when I did:
```
import os
os.chdir('/home/jail/dlusers/ajacques/notebooks_20230123_193855/04_HowTos/DataReduction/PyrafGMOS/')
```
Or even:
```
import os
os.chdir('./')
```
I'll review the rest of the notebook, but this is something that will need to be added in case other users are running on their home directory.

**Comment by vmplacco** [comment]
Great, thanks!

Yes, we can add an extra cell there.

Best,
Vini

**Comment by rnikutta** [comment]
So, it *should* work in the directory in which the NB is. Mike made a change to the kernel specifically for that.

@mjfitzpatrick , can you please work with Alice to identify what's causing the regression?

Thanks,
Robert

**Comment by jacquesalice** [comment]
@bmerino95 @vmplacco my other comments:
1. Can you add a bit more description about what is happening in each cell? For instance, in the Basic Reduction part what do the parameters being passed to `gsreduce` and `gsflat` represent (i.e. `fl_flat`, `fl_gmosaic`, `fl_fixpix`, etc)?
2. In the same cell, I can see that the first 3 `inimages` are the files that were downloaded to my directory in the previous cell, but where do `inflats="gsN20190302S0250"` and `inimages="gsN20190302S0248"` come from?
3. Again in this same section, you should inform the user that there will be a few dozen FITS files and temporary files created/removed from running this cell.
4. In the "Display fully reduced spectrum" section, can you briefly explain how you are calculating the wavelength values from CD1_1 and CRVAL1? 
5. In the same section, change `data = iraf_out[2].data` to `flux = iraf_out[2].data` for clarity on what the variable contains.

Thanks! :)

**Comment by vmplacco** [comment]
Thanks @jacquesalice! I should be able to work on this on Thursday (there is an AURA meeting tomorrow and I am helping out with a NOIRLab Open House) and send it back for a final review.

**Review by jacquesalice — APPROVED** [review]
Looks great @vmplacco thank you! I'm approving the PR but I think @rnikutta wanted to take a look as well before we merge into production.

**Comment by vmplacco** [comment]
Great, thanks! The DRAGONS one is coming soon...

**Comment by rnikutta** [comment]
Thank you @vmplacco and @jacquesalice . I only cleared the outputs, and will now merge. (We most often leave the output in a NB, but these ones here are very long).

**Pull request merged**
