### PR TITLE
NB Disclaimer and Acks update - DH batch

### PR DESCRIPTION
**Pull request by kareninysimba**
@i-olin, please kindly review this PR.

Section _Disclaimer & attribution_ has been updated with the new one indicated by Robert N. for 11 assigned notebooks and their html versions were updated accordingly:

./04_HowTos/AuthClient/How_to_use_the_Data_Lab_AuthClient.ipynb
./04_HowTos/CrossmatchTables/Examples_using_pre_crossmatched_tables.ipynb
./04_HowTos/CrossmatchTables/How_to_crossmatch_tables.ipynb
./04_HowTos/CrossmatchTables/How_to_use_pre_crossmatched_tables.ipynb
./04_HowTos/QueryClient/How_to_query_DESI_EDR_Data.ipynb
./04_HowTos/QueryClient/How_to_use_the_Data_Lab_QueryClient.ipynb
./04_HowTos/SiaService/How_to_use_the_Simple_Image_Access_service.ipynb
./04_HowTos/SPARCL/How_to_use_SPARCL.ipynb
./04_HowTos/SPARCL/Plot_SPARCL_Spectra_with_Jdaviz.ipynb
./04_HowTos/SPARCL/Plot_SPARCL_Spectra_with_Prospect.ipynb
./04_HowTos/StoreClient/How_to_use_the_Data_Lab_StoreClient.ipynb

### CODE REVIEW

**Review by i-olin — APPROVED** [review]
Looks good.

**Comment by rnikutta** [comment]
Hi @kareninysimba and @i-olin I'm seeing a bunch of conflict-related strings in this batch. (Look for strings like

```
<<<<<<< HEAD
    "__version__ = '20240603' # yyyymmdd\n",
=======
    "__version__ = '20240604' # yyyymmdd\n",
>>>>>>> 10486aa (NB Disclaimer and Acks update - DH batch (no output clearing))
```

Best if you re-do the batch. Pull a fresh branch from master branch @kareninysimba

**Review by rnikutta — CHANGES_REQUESTED** [review]
See my previous comment for requested changes.

**Comment by kareninysimba** [comment]
Argh!... on it now

**Pull request closed without merging**
