### PR TITLE
Ipywidgets matplotlib.pyplot updates

### PR DESCRIPTION
**Pull request by marcodatadev**
These changes are needed due to updates in the Ipywidgets and Matplotlib libraries.

We are fixing the errors reported by Justine Schane and Robert Sparks, where the slides were duplicating images.

### CODE REVIEW

**Comment by marcodatadev** [comment]
Hi @jacquesalice and @rnikutta

Could yo please review this PR?

Regards,

Marco Moreno

**Comment by marcodatadev** [comment]
Hi Robert,

Thank you for your review. I appreciate it.

Could you be so kind as to ignore the changes in NB
*06_EPO/TeenAstronomyCafe/07_Large_Scale_Structure_of_the_Universe/Large_Scale_Structure_of_the_Universe.ipynb*
and only update the changes in the NBs in the* e-TeenAstronomyCafe*? I
tested all the changes in the NBs in * e-TeenAstronomyCafe* , and they are
working properly.

Thanks

Regards/Saludos,

*Marco Moreno*
Web Projects Coordinator | Enciso Systems
A: Calle 35B # 19D - 40 | Villavicencio, Colombia
C: +57 317 6394548 | W: encisosystems.com

✨ Follow us: encisosystems.com/social ✨

**Comment by rnikutta** [comment]
Hi @marcodatadev Of course! But could you please add another commit to your PR where you undo/revert the changes to the NB 06_EPO/TeenAstronomyCafe/07_Large_Scale_Structure_of_the_Universe/Large_Scale_Structure_of_the_Universe.ipynb

Then I can merge the rest very simply.

Thanks!

**Comment by marcodatadev** [comment]
Hi @rnikutta,

I reverted the commit, and the PR has been updated. The NBs with changes are all from the folder  e-TeenAstronomyCafe.

Thanks

**Review by rnikutta — APPROVED** [review]
Thank you @marcodatadev . Merging in a second!

**Comment by marcodatadev** [comment]
Many thanks @rnikutta

Regards/Saludos,

*Marco Moreno*
Web Projects Coordinator | Enciso Systems
A: Calle 35B # 19D - 40 | Villavicencio, Colombia
C: +57 317 6394548 | W: encisosystems.com

✨ Follow us: encisosystems.com/social ✨

**Pull request merged**
