### PR TITLE
DESI EDR Notebooks

### PR DESCRIPTION
**Pull request by Ragadeepika-Pucha**
The notebooks currently work in db01 -- however, the Intro notebook still needs a DESI Kernel to work.
Both the notebooks need to be tested after the staging is complete.

### CODE REVIEW

**Review by rnikutta — CHANGES_REQUESTED** [review]
Thank you @Ragadeepika-Pucha for these NBs. Comments in addition to Alice and Stephanie's reviews:
- In the first cells (meta data), remove the in-line comments; these are for the NB template (and yes, we have them in many NBs, but I hope we can start cleaning them up)

02 NB:
- I think it would be helpful if this NB linked (early on) to the "How to use SPARCL" NB; otherwise some of the operations (e.g., search constraints, client.find() method, etc.) may be a bit opaque.
- What does this sentence say/mean? "We further compare the spectral access via SPARCL."
- "Stellar spectra informs us about their ages, temperatures, and chemical compositions;" --> "Stellar spectra inform us about the stars' ages, temperatures, and chemical compositions;"
- "while galaxy spectra provides" --> "provide"
- "Spectroscopic surveys therefore enables" --> "enable"
- Please check the entire NBs for such singular/plural mismatches.
- In the comparison table between SDSS/BOSS and DESI, you could save some typing by writing instead: `Fiber diameter | 3" (2") | 1.5"`
- In the same table, capitalize only the first word in "Wavelength coverage", "Spectral resolution", "Spatial density".
- "focusing on the flux and the resolution that is achievable from the two surveys." --> "... and the spectral resolution ..."
- Imports: rather than the very general `import warnings; warnings.filterwarnings('ignore')` (which silences all warnings), better use here the specific: `np.seterr(divide='ignore')` instead.
- Imports: don't import specclient; it's not being used.
- Imports: drop this line (these aren't used in the NB): `from astropy.convolution import convolve, Gaussian1DKernel`
- Remove this cell" `#!pip install sparclclient==1.2.0b3.dev9`
- "Both SDSS and DESI have spectra in this region, and is therefore perfect for our comparison." --> "Both SDSS and DESI have spectra in this region. It is is therefore perfect for our comparison."
- Minor thing regarding the Ra/Dec scatterplot (first figure), but the red and green symbols are hard to tell apart for people with red-green color blindness (somewhere between 1 and 8%, depending on gender and ethnicity).
- Parentheses around a triple-quoted query string are not needed.
- Section title "Spectral Access" should be "Spectrum Access" or "Spectra Access", or even better in active voice: "Accessing Spectra".
- "Next, we compre" --> "compare"

I'll review the 01 NB later tonight.

**Comment by Ragadeepika-Pucha** [comment]
@rnikutta @jacquesalice @stephjuneau - Thank you for the comments! I updated the notebooks based on all the suggestions.

**Comment by jacquesalice** [comment]
@Ragadeepika-Pucha can you please also resolve the "conflicts" that the new Emission Line Galaxies notebook has with the old one?

**Comment by Ragadeepika-Pucha** [comment]
@jacquesalice - I am not sure how to resolve the "conflicts" - I did a pull from the master - but it still says - "everything up to-date and nothing to commit"

**Comment by rnikutta** [comment]
Hi @Ragadeepika-Pucha and @jacquesalice I'll resolve the conflict; it's from Igor's/mine fixes to the the deprecated np.warnings.filterwarnings().

**Comment by rnikutta** [comment]
@Ragadeepika-Pucha , @jacquesalice , @stephjuneau

A small snafu. I think the 03_ScienceExamples/EmLineGalaxies/01_EmLineGalaxies_SpectraStack.ipynb notebook  uses 'id' in INCLUDE, but that was renamed, right? See in function get_sdss_spectra():

```
## Retrieve the spectra
    res = client.retrieve_by_specid(specid_list = [specobjid], 
                                    include = ['id', 'redshift', 'flux', 'wavelength', 'model', 'ivar'],
                                    dataset_list = ['SDSS-DR16', 'BOSS-DR16'])
```

and then the call gives:

```
wavelength, flux, model, ivar = get_sdss_spectra(specobjid[index], rest_frame = True)

BadInclude: [BADINCL] The INCLUDE list (flux,id,ivar,model,redshift,wavelength) contains invalid data field names for Data Sets (BOSS-DR16,SDSS-DR16). Unknown fields are: id.
```

**Comment by Ragadeepika-Pucha** [comment]
@rnikutta - I think SPARCL has changed since then. I will make the changes and commit them to this PR itself.

**Comment by Ragadeepika-Pucha** [comment]
@jacquesalice @rnikutta @stephjuneau - I updated both the emission-line notebooks to work with the latest SPARCL version - but, for the stacking notebook, when I am trying to get 100 spectra of SDSS sources, only >90% of the spectra are getting retrieved. Not all the spectra are getting retrieved from SDSS+BOSS. I am not able to think of any reason why that is.

**Comment by Ragadeepika-Pucha** [comment]
I updated the second emission-line galaxies notebook - the multiwavelength cutouts one - to work with the latest SPARCL version. However, the Spectral stacking notebook is still producing errors.

**Comment by rnikutta** [comment]
@Ragadeepika-Pucha Looks like the EmLines 01 NB (stacking) has the same issue in function get_sdss_spectra(), i.e. INCLUDE has 'id' in it.

**Comment by rnikutta** [comment]
@Ragadeepika-Pucha I'll log off for tonight. Maybe you can make the final fix tomorrow morning then? Thanks!

**Comment by Ragadeepika-Pucha** [comment]
Yes - but I fixed that. The issue now is that not all the spectra are getting retrieved for the stacking function. I am getting the following error:
image
The input is a table with 100 sources, but SPARCL is retrieving only 95-98 (based on my tests) spectra.

**Comment by rnikutta** [comment]
Unless I'm doing something wrong, on desi_edr_raga branch, the EmLine 01 stacking NB still shows 'id' in 'include=' in the get_sdss_spectra() function. (It is fixed to 'sparcl_id' in the 02 NB though. Also in function stack_spectra().

Regarding the 2nd error (after I changed both 'id' to 'sparcl_id'): it fails at index 337 (when starting with zero). Maybe for the given sparcl_id list, some spectra were missing or not retrieved?

**Comment by stephjuneau** [comment]
I'm going to resolve conflicts and merge this one and I have found a fix for the EmLine SDSS Stacking notebook but I'd rather create its own branch+PR if that's OK? @jacquesalice or @rnikutta, do you agree?

**Comment by rnikutta** [comment]
Ok thanks @stephjuneau , I won't do the resolution then.

**Comment by stephjuneau** [comment]
@rnikutta I resolved the conflicts but Merging is still blocked by your requested changes although I think @Ragadeepika-Pucha did make the changes.

**Comment by rnikutta** [comment]
Ok I merged bypassing the outstanding review request. Can you please verify that the merge went through on Github etc.?

**Comment by stephjuneau** [comment]
@rnikutta The GitHub version looks good! Thanks so much!!

**Pull request merged**
