### PR TITLE
Remove LS DR3 section, use pre-crossmatched table

### PR DESCRIPTION
**Pull request by jacquesalice**
Wait to merge until after LS DR3 through DR7 is removed from db02 and db03.

Assigning to @rnikutta and @stephjuneau to review.

### CODE REVIEW

**Comment by rnikutta** [comment]
@jacquesalice What's this PR? Or what's its status? (Note that it currently has conflicts with master)

**Comment by jacquesalice** [comment]
@rnikutta This PR is to update the StarGalQSO science example notebook with:
- Removal of the full LS DR3 query section.
- In the "Adding spectroscopic information from SDSS" section, addition of the query that uses the SDSS DR17 x LS DR9 pre-crossmatched table to plot a color-color diagram and compare with the user-contributed version that uses SDSS DR3 and LS DR3.

And yes, I commented that this notebook would have conflicts with master in [PR#196](https://github.com/astro-datalab/notebooks-latest/pull/196) and you replied:
> Let's leave the NB here, and in #195 and we'll worry about merge conflicts when we merge the PRs. Whatever merge comes second, we can edit the NB to resolve and conflicts (I volunteer myself).

**Comment by rnikutta** [comment]
Oh, right! Thanks for reminding me. I'll resolve the conflicts.

**Review by rnikutta — APPROVED** [review]
Conflicts (hopefully) resolved.

**Pull request merged**
