### PR TITLE
TAC Updates

### PR DESCRIPTION
**Pull request by avichalk**
@jacquesalice, @rnikutta

### CODE REVIEW

**Comment by jacquesalice** [comment]
Hi @avichalk , are these notebooks supposed to be updating the ones in the `TeenAstronomyCafe` directory or the `e-TeenAstronomyCafe` directory? Because they look like the notebooks in the `e-TeenAstronomyCafe` dir, but this PR is to update the ones in `TeenAstronomyCafe`...

**Comment by avichalk** [comment]
Hi,

In the instructions I was forwarded I was told to replace the notebooks in the TeenAstronomyCafe directory (6_EPO/TeenAstronomyCafe/). But looking through the notebooks in the e-TeenAstronomyCafe directory, those are much closer to the ones I've been working on. Should my pull request have been for the e-TeenAstronomyCafe directory? The notebooks I edited were all on Google Collab, if that helps narrow it down.

Thanks.

**Comment by rnikutta** [comment]
Hi @avichalk , the NBs in 'e-TeenAstronomyCafe' are meant to be run on Google Collab. The NBs in 'TeenAstronomyCafe' might run on Collab, but were never tested nor intended for Collab.
Please double-check with, e.g. Connie Walker, Mark Newhouse, and @DavidVargasMora . If needed, please make a new PR for the 'e-' directory, and close this one.

**Comment by avichalk** [comment]
Yes, I think it is the e- directory. I will close this request and open a new one. Sorry for the inconvenience.

**Pull request closed without merging**
