### PR TITLE
Add __nbid__ to all NBs. Template has '0000'. No IDs for EPO notebook…

### PR DESCRIPTION
**Pull request by rnikutta**
…s (they aren't controlled by us). No updates to NB version strings.

### CODE REVIEW

**Comment by rnikutta** [comment]
@kareninysimba @jacquesalice @bmerino95 could you please review this PR? It adds `__nbid__ = '0034'` etc to every NB (first cell with the NB metadata). The template NB file has nbid '0000', the rest are incremental numbers, but formatted as a 4-digit long zero-padded string.

I also had to update one NB (1_GOGREEN...) because the metadata cell had the variables without the double-underscores.

Finally, I on purpose didn't update the `__version__` strings (except int he template ipynb file).

Thanks!

**Comment by rnikutta** [comment]
Thanks @jacquesalice . Good catch! Turns out I had another non-tracked ipynb file in my clone when I generated the list of files to number... and that one got 0031. I'll run the thing again today.

**Comment by rnikutta** [comment]
@jacquesalice @bmerino95 @kareninysimba how about now?

**Review by bmerino95 — APPROVED** [review]
Looks good! 👍🏼

**Review by kareninysimba — APPROVED** [review]
Looks good. 0031 is there now 👍🏻

**Comment by rnikutta** [comment]
Thanks all. Made one more commit to add a csv file (`nbid.csv`) that maps the nbid values to the specific NB files (as discussed in the DEV meeting today). Will merge now.

**Pull request merged**
