### PR TITLE
NB Disclaimer and Acks update - BM batch

### PR DESCRIPTION
**Pull request by bmerino95**
Updated the Disclaimer and Acks for 11 notebooks.

### CODE REVIEW

**Comment by rnikutta** [comment]
@bmerino95 one NB in your batch has a conflict, likely because I just merged your DRAGONS NBs, and one of them was this very NB. I'll attempt to resolve it by pushing to your branch.

And I'll review the entire batch (today and/or tomorrow).

**Comment by rnikutta** [comment]
@bmerino95 I *think* I resolved the merge conflict correctly. I'm still checking the offending NB `04_HowTos/DataReduction/DRAGONS_reduction_examples/GMOS_Imaging_StarryField/GMOS_Imaging_StarryField.ipynb` --> It seems to have both your Disclaimer & Acks changes, and the updated language from David's comments.

If you could also please take a quick look and let me know whether things look alright? Thanks!

**Comment by bmerino95** [comment]
Hey @rnikutta. I just looked through the GMOS_Imaging_StarryField.ipynb and it looks good. The disclaimer/acknowledgments are updated and David’s suggestions are present.

**Comment by rnikutta** [comment]
Thanks @bmerino95 I will attempt a merge! Fingers crossed..

**Pull request merged**
