### PR TITLE
removed duplicate notebook

### PR DESCRIPTION
**Pull request by KeenanFiedler**

### CODE REVIEW

**Review by rnikutta — APPROVED** [review]
Thanks @KeenanFiedler !
@stephjuneau and @jacquesalice as discussed earlier, the GaiaDR2 NB is identical to DR3, and is basically superseded. Please approve this deletion PR.

**Review by stephjuneau — APPROVED** [review]
Removing the duplicate notebook is a good idea. Looks good!

**Comment by stephjuneau** [comment]
@rnikutta not sure if it's better to merge this one before or after PR #220 to avoid a conflict as they both affect the same notebooks (Gaia DR2).

**Comment by rnikutta** [comment]
@stephjuneau we should probably first merge the other ones, then this one to remove the DR2 NB.

**Comment by jacquesalice** [comment]
@rnikutta should we also remove these other duplicated notebooks?

1. [Dwarf Galaxies in DELVE DR1](https://github.com/astro-datalab/notebooks-latest/blob/master/03_ScienceExamples/DwarfGalaxies/DwarfGalaxiesInDelveDr1.ipynb) 
---> Duplicated in [Dwarf Galaxies in DELVE DR2](https://github.com/astro-datalab/notebooks-latest/blob/master/03_ScienceExamples/DwarfGalaxies/DwarfGalaxiesInDelveDr2.ipynb)
2. [Dwarf Galaxies in NSC DR1](https://github.com/astro-datalab/notebooks-latest/blob/master/03_ScienceExamples/DwarfGalaxies/DwarfGalaxiesInNscDr1.ipynb)
---> Duplicated in [Dwarf Galaxies in NSC DR2](https://github.com/astro-datalab/notebooks-latest/blob/master/03_ScienceExamples/DwarfGalaxies/DwarfGalaxiesInNscDr2.ipynb)

**Comment by rnikutta** [comment]
I think that's a good idea @jacquesalice . @KeenanFiedler would you mind adding to this PR the deletion of the two NBs that Alice suggested? We'll merge then as one PR that removes 3 obsolete NBs.

**Comment by rnikutta** [comment]
Thanks @KeenanFiedler !

**Pull request merged**
