### PR TITLE
Update NB template: disclaimer and acks, available datasets section, …

### PR DESCRIPTION
**Pull request by rnikutta**
…commented out login cell.

### CODE REVIEW

**Comment by rnikutta** [comment]
@stephjuneau @jacquesalice @galaxyumi I've updated the DL NB template:
- Linked to our new Disclaimers page
- Added verbatim our detailed Acks requirements

I also edited the cell that lists all available datasets, and commented out the Login cell.

Please kindly review the template NB. The Disclaimer and Acks cell will be used to update all other NBs in the next step.

**Review by jacquesalice — APPROVED** [review]
Looks good to me, thanks Robert!

**Review by stephjuneau — COMMENTED** [review]
Hi @rnikutta , the new acknowledgements all look good!

I know that not the main point of this PR but I was just curious about why commenting our the Authentication part? Shouldn't the line `ac.whoAmI()` just result in "anonymous" when the user is not authenticated, which would be useful to know for the user in any scenario?

**Comment by rnikutta** [comment]
It's a good point.. The reason I commented it out is because in most cases (I think) a user running a NB will be logged in, including when we test the NBs ourselves (which then always evaluates to my username...). To avoid having to explicitly use ac.logout(), then remove that code again, and re-run the NB, I thought it was easier to comment out the cell. The text just before the auth cell actually says explicitly to un-comment the cell, should a login be needed.

What do you think?

**Comment by jacquesalice** [comment]
> It's a good point.. The reason I commented it out is because in most cases (I think) a user running a NB will be logged in, including when we test the NBs ourselves (which then always evaluates to my username...). To avoid having to explicitly use ac.logout(), then remove that code again, and re-run the NB, I thought it was easier to comment out the cell. The text just before the auth cell actually says explicitly to un-comment the cell, should a login be needed.
> 
> What do you think?

If we comment it out in this notebook, should we comment it out in all notebooks?

**Comment by rnikutta** [comment]
I've been suggesting as much in most of the NBs that I've been reviewing over the past months..

**Review by stephjuneau — APPROVED** [review]

**Comment by rnikutta** [comment]
Thank you, will merge!

**Pull request merged**
