### PR TITLE
Remove %%time in group 1 of NBs. Update version strings. Minor cleanu…

### PR DESCRIPTION
**Pull request by rnikutta**
…p here and there.

### CODE REVIEW

**Comment by rnikutta** [comment]
@jacquesalice and @kareninysimba please review my group of NBs. Don't merge. Thanks.

**Review by jacquesalice — CHANGES_REQUESTED** [review]
Hi @rnikutta I think it all looks good! Though since I've made further changes to the `03_ScienceExamples/StarGalQSOSeparation/StarGalQsoLSDR9.ipynb` notebook in
 [PR#195](https://github.com/astro-datalab/notebooks-latest/pull/195), maybe we should remove it from this PR so it doesn't overwrite my changes? I've made sure to remove `%%time`

**Comment by rnikutta** [comment]
Thanks @jacquesalice . Let's leave the NB here, and in #195 and we'll worry about merge conflicts when we merge the PRs. Whatever merge comes second, we can edit the NB to resolve and conflicts (I volunteer myself).

**Review by jacquesalice — APPROVED** [review]

**Comment by rnikutta** [comment]
@kareninysimba and @jacquesalice , I added a commit that removes the instances of "this cell will take N minutes" etc. (for my batch of NBs)

**Pull request merged**
