### PR TITLE
General clean-up

### PR DESCRIPTION
**Pull request by jacquesalice**
Updated things like:
- http --> https for Astro Data Lab links
- Added link to Astro Archive
- Authentication section

### CODE REVIEW

**Comment by jacquesalice** [comment]
@rnikutta I went through all of the notebooks and updated the authentication section, replaced http with https in our disclaimers link, and did some other minor clean-up where needed (i.e. fixing typos, uniform formatting, adding tags...). I also updated the README file.

**Review by rnikutta — CHANGES_REQUESTED** [review]
Thank you @jacquesalice ! I've tried a small sample of the updated NBs (not all!), and all looked good. I took a few notes, but they are for a later PR, not urgent.

The only thing I request to change: for the NB 03_ScienceExamples/LargeScaleStructure/LargeScaleStructureSdssLs.ipynb , please execute the NB end to end, then clear the output of the cell that contains the 3d visualization, save the ipynb, and export html also without the 3d. With the 3d viz, the NB file is much much larger (too large for comfort).

Thanks!

**Comment by jacquesalice** [comment]
@rnikutta ok done!

**Review by rnikutta — APPROVED** [review]

**Comment by rnikutta** [comment]
Thank you @jacquesalice , merged!

**Pull request merged**
